# Generated by Django 4.2.16 on 2024-09-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_category_popularity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', '-stock', '-price']},
        ),
    ]
