# Generated by Django 4.2.16 on 2024-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
