# Generated by Django 4.2.16 on 2024-09-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_count',
        ),
    ]
